import {createClient} from '@supabase/supabase-js';
export type Lang='bn'|'en';
export type Event={id?:string;owner_id?:string;title:string;host_names:string;kind:string;event_date:string;venue:string;address:string;message:string;theme:string;language:Lang;published:boolean;album_enabled:boolean;created_at?:string};
export type Guest={id:string;event_id:string;name:string;max_party:number;relationship:string;personal_message?:string;token:string;status:string;party_size:number;note:string;opened_at?:string;created_at?:string};
export type Photo={id:string;name:string;url:string;size:number;created_at:string;featured?:boolean};
export const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL || '';
const KEY=import.meta.env.VITE_SUPABASE_KEY || '';
export const db=SUPABASE_URL&&KEY?createClient(SUPABASE_URL,KEY):null;
export const themes=[{id:'neel',bn:'নীলকাব্য',en:'Blue poetry',label:'SIGNATURE',color:'#1835b9'},{id:'alta',bn:'আলতা',en:'Alta',label:'BENGALI CLASSIC',color:'#a32535'},{id:'bon',bn:'বনলতা',en:'Bonolota',label:'BOTANICAL',color:'#234d3c'},{id:'noor',bn:'নূর',en:'Noor',label:'TIMELESS',color:'#422c66'}];
export const demoEvent:Event={title:'আমাদের বিয়ে',host_names:'আরিব & মেহরিন',kind:'wedding',event_date:'2026-12-18T19:00',venue:'সেনামালঞ্চ',address:'ঢাকা ক্যান্টনমেন্ট, ঢাকা',message:'জীবনের নতুন অধ্যায়ে পা রাখতে যাচ্ছি আমরা। এই আনন্দের মুহূর্তে আপনার উপস্থিতি আমাদের আয়োজনকে পূর্ণতা দেবে।',theme:'neel',language:'bn',published:false,album_enabled:false};
export function dateLabel(value:string,lang:Lang){if(!value)return lang==='bn'?'তারিখ বেছে নিন':'Choose a date';return new Date(value.length===16?value+'+06:00':value).toLocaleDateString(lang==='bn'?'bn-BD':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Dhaka'});}
export function timeLabel(value:string,lang:Lang){return value?new Date(value.length===16?value+'+06:00':value).toLocaleTimeString(lang==='bn'?'bn-BD':'en-GB',{hour:'numeric',minute:'2-digit',timeZone:'Asia/Dhaka'}):'';}
export function wording(lang:Lang,tone:string,kind:string){const type=kind==='wedding'?(lang==='bn'?'জীবনের নতুন অধ্যায়ে':'a new chapter of our lives'):(lang==='bn'?'আমাদের আনন্দের আয়োজনে':'our special celebration');if(lang==='bn')return tone==='friend'?`প্রিয় মানুষগুলোকে নিয়েই তো আনন্দ! ${type} তোমাকে পাশে চাই। সময় করে চলে এসো, অনেক গল্প আর হাসি জমা আছে।`:tone==='warm'?`${type} আপনাকে আন্তরিকভাবে আমন্ত্রণ জানাচ্ছি। আপনার উপস্থিতি আর ভালোবাসায় দিনটি হয়ে উঠুক আরও সুন্দর।`:`সশ্রদ্ধ আমন্ত্রণ। ${type} আপনার সানুগ্রহ উপস্থিতি একান্তভাবে কামনা করছি। আমাদের আনন্দের অংশ হয়ে আয়োজনকে পূর্ণতা দিন।`;return tone==='friend'?`The best moments are the ones we share. Join us for ${type} — we have a seat, a smile, and plenty of stories waiting for you.`:tone==='warm'?`We would love to have you with us for ${type}. Your presence will make this day even more special.`:`You are cordially invited to join us for ${type}. It would be our pleasure to celebrate this occasion in your company.`;}
export function inviteUrl(token:string){return `${location.origin}/i/${token}`;}
export async function guestApi(action:string,payload:Record<string,unknown>){if(!db)throw new Error('Service is not connected yet.');const {data:{session}}=await db.auth.getSession();const response=await fetch(`${SUPABASE_URL}/functions/v1/daakdio-guest`,{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,...(session?{Authorization:`Bearer ${session.access_token}`}:{})},body:JSON.stringify({action,...payload})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again.');return result;}
export async function uploadPhoto(file:File,token:string){if(file.size>10*1024*1024)throw new Error('Pilot limit: 10 MB per photo.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Please use JPG, PNG or WebP.');const signed=await guestApi('upload',{token,name:file.name,size:file.size,type:file.type});const {error}=await db!.storage.from('daakdio-albums').uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(error)throw error;await guestApi('complete_upload',{token,id:signed.id});}
