import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
type Props={theme:string;paused?:boolean;inline?:boolean};
function petalGeometry(){const positions:number[]=[],indices:number[]=[];const rows=14,cols=8;for(let i=0;i<=rows;i++){const t=i/rows;for(let j=0;j<=cols;j++){const u=j/cols*2-1;const w=Math.pow(Math.sin(Math.PI*t),.75)*.38;positions.push(u*w,t*1.25,.2*Math.sin(Math.PI*t)-.32*t*t+.15*u*u)}}for(let i=0;i<rows;i++)for(let j=0;j<cols;j++){const a=i*(cols+1)+j,b=a+cols+1;indices.push(a,b,a+1,b,b+1,a+1)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();return g}
export default function Scene({theme,paused=false,inline=false}:Props){const host=useRef<HTMLDivElement>(null),pausedRef=useRef(paused);const [failed,setFailed]=useState(false);useEffect(()=>{pausedRef.current=paused},[paused]);
useEffect(()=>{const container=host.current;if(!container)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:window.devicePixelRatio<2,powerPreference:'low-power'});}catch{setFailed(true);return}setFailed(false);renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x000000,0);container.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,60);camera.position.set(0,0,12);const root=new THREE.Group();scene.add(root);const light=new THREE.DirectionalLight(0xfff4df,3);light.position.set(-3,5,7);scene.add(light,new THREE.AmbientLight(0xffffff,1.6));const fill=new THREE.PointLight(theme==='neel'?0x8a8aff:0xffc5a0,18,20);fill.position.set(5,-2,4);scene.add(fill);
const dark=theme==='neel'||theme==='noor';const pale=new THREE.MeshStandardMaterial({color:theme==='bon'?0xffe5e1:theme==='alta'?0xffb526:0xf4e5d2,side:THREE.DoubleSide,roughness:.48,metalness:.12});const alt=new THREE.MeshStandardMaterial({color:theme==='alta'?0xf37326:theme==='bon'?0xe8b7ba:0xc9b6eb,side:THREE.DoubleSide,roughness:.6});const gold=new THREE.MeshStandardMaterial({color:0xd5a85e,metalness:.7,roughness:.3});const green=new THREE.MeshStandardMaterial({color:0x7b9471,side:THREE.DoubleSide,roughness:.7});const petal=petalGeometry();const sphere=new THREE.SphereGeometry(.18,12,8);const floating:{obj:THREE.Object3D;x:number;y:number;z:number;phase:number;speed:number}[]=[];const attach=(obj:THREE.Object3D,x:number,y:number,z:number,s=1,phase=0)=>{obj.position.set(x,y,z);obj.scale.setScalar(s);root.add(obj);floating.push({obj,x,y,z,phase,speed:.3+phase%3*.05})};
function flower(size=1,marigold=false){const g=new THREE.Group();const layers=marigold?3:2;for(let k=0;k<layers;k++){const n=marigold?10:7;for(let i=0;i<n;i++){const m=new THREE.Mesh(petal,k===0?pale:alt);m.rotation.z=i/n*Math.PI*2+k*.4;m.rotation.x=k===0?.15:-.1;m.scale.setScalar((1-k*.25)*(marigold?.55:1));m.position.z=k*.08;g.add(m)}}const center=new THREE.Mesh(sphere,gold);center.scale.setScalar(marigold?.7:1);center.position.z=.12;g.add(center);g.scale.setScalar(size);return g}
function leaf(){const g=new THREE.Group();for(let i=0;i<5;i++){const m=new THREE.Mesh(petal,green);m.scale.set(.3,.65,.7);m.rotation.z=i%2===0?-.6:.6;m.position.set(i%2===0?-.15:.15,i*.45,0);g.add(m)}return g}
function ring(r:number,t=.012){return new THREE.Mesh(new THREE.TorusGeometry(r,t,8,100),gold)}
if(theme==='bon'){attach(flower(),-3.15,-1.6,1,1.35,1);attach(flower(),3,2.1,0,1.15,2);attach(flower(),-3.4,2.3,-1,.52,4);attach(flower(),3.4,-2.4,1,.75,3);attach(leaf(),-3.1,-2.8,-.4,1.4,5);attach(leaf(),3.3,-1.7,-.2,1.4,7)}
else if(theme==='alta'){for(let i=0;i<7;i++){const f=flower(1,true);attach(f,Math.cos(i*.53)*4.2,3.9-Math.abs(Math.cos(i*.53))*.7,-1,.65,i)}attach(flower(1,true),-3.3,-2.5,0,1.6,2);attach(flower(1,true),3.3,-2,1,1.1,4);
function doll(color:number,x:number){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color,roughness:.6});const body=new THREE.Mesh(new THREE.ConeGeometry(.4,1.25,20),mat);g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.24,18,12),new THREE.MeshStandardMaterial({color:0xdfad82,roughness:.7}));head.position.y=.82;g.add(head);const band=ring(.24,.04);band.rotation.x=Math.PI/2;band.position.y=.98;g.add(band);attach(g,x,-1.8,1,.8,x+5)}doll(0xe9bd61,-2.1);doll(0xa92d39,2.1)}
else if(theme==='noor'){for(let i=0;i<4;i++){const arch=new THREE.Group();const top=new THREE.Mesh(new THREE.TorusGeometry(2.3-i*.2,.016,6,80,Math.PI),gold);arch.add(top);for(const x of [-1,1]){const bar=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,4,6),gold);bar.position.set(x*(2.3-i*.2),-2,0);arch.add(bar)}attach(arch,0,0,-i*.65,1,i)}for(let i=0;i<8;i++){const gem=new THREE.Mesh(new THREE.OctahedronGeometry(.12,0),gold);attach(gem,Math.sin(i*2.4)*3.6,Math.cos(i*1.4)*3.2,1,.8,i)}attach(flower(),-3,-2,1,.7,4);attach(flower(),3,1.8,0,.6,2)}
else{const r=ring(2.6,.009);r.rotation.set(.35,.25,.15);attach(r,0,0,-1,1,1);const r2=ring(3.15,.005);r2.rotation.set(-.4,-.4,0);attach(r2,0,0,-2,1,2);const moon=new THREE.Mesh(new THREE.SphereGeometry(.24,24,16),new THREE.MeshStandardMaterial({color:0xf1dbb1,emissive:0xd8b16f,emissiveIntensity:.3}));attach(moon,2.8,2.2,-1,1,5);attach(flower(),-3.1,-2.05,1,1.2,3);attach(flower(),3.05,1.9,0,.9,2);attach(flower(),3.5,-2.6,-1,.6,4)}
const positions:number[]=[];for(let i=0;i<(dark?170:55);i++){const a=i*2.399963;const r=2+(i%31)/31*5;positions.push(Math.cos(a)*r,Math.sin(a)*5,((i*7)%13)/3-5)}const pointsG=new THREE.BufferGeometry();pointsG.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));const pointsM=new THREE.PointsMaterial({color:dark?0xf9d99a:0xb28563,size:dark?.025:.025,transparent:true,opacity:dark?.8:.55,depthWrite:false});const stars=new THREE.Points(pointsG,pointsM);root.add(stars);
const loose:THREE.Mesh[]=[];for(let i=0;i<14;i++){const m=new THREE.Mesh(petal,i%2?pale:alt);m.scale.set(.09,.13,.12);m.rotation.set(i*.4,i*.8,i);m.position.set(Math.sin(i*2.4)*4.5,Math.cos(i*1.7)*4,(i%5)-2);root.add(m);loose.push(m)}
let target=0,progress=0,mouseX=0,mouseY=0,visible=true,raf=0,last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const resize=()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.position.z=w<600?15.5:12;camera.updateProjectionMatrix();render(performance.now(),true)};const scroll=()=>{target=inline?0:Math.min(window.scrollY/Math.max(innerHeight,1),5)};const pointer=(e:PointerEvent)=>{mouseX=(e.clientX/innerWidth-.5)*.4;mouseY=(e.clientY/innerHeight-.5)*.25};const contextLost=(e:Event)=>{e.preventDefault();setFailed(true);cancelAnimationFrame(raf)};const visibility=()=>{if(!document.hidden){last=0;cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}};function render(time:number,force=false){const still=reduced.matches||pausedRef.current;const t=still?0:time*.0003;progress+=(target-progress)*.045;root.position.y=progress*.26;root.rotation.y=still?0:mouseX*.16+Math.sin(t*.3)*.05;root.rotation.x=still?0:mouseY*.12;floating.forEach(({obj,x,y,z,phase,speed},i)=>{obj.position.set(x+Math.sin(t*speed+phase)*.12,y+Math.sin(t+phase)*.12-progress*(i%2===0?.18:-.13),z+Math.sin(progress*.7+phase)*.25);if(!(theme==='noor'&&i<4))obj.rotation.z=Math.sin(t*.6+phase)*.15+progress*(i%2===0?.09:-.07)});stars.rotation.z=t*.018+progress*.04;loose.forEach((m,i)=>{m.position.y=(((i*.73-t*.4+progress*.5)%9)+9)%9-4.5;m.rotation.z=i+t*.5});if(force||visible)renderer.render(scene,camera)}function tick(time:number){if(document.hidden)return;raf=requestAnimationFrame(tick);if(time-last<33)return;last=time;if(visible&&(!pausedRef.current&&!reduced.matches||Math.abs(target-progress)>.005))render(time)}
const observer=new ResizeObserver(resize);observer.observe(container);const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting},{threshold:0});io.observe(container);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('pointermove',pointer,{passive:true});document.addEventListener('visibilitychange',visibility);renderer.domElement.addEventListener('webglcontextlost',contextLost);resize();raf=requestAnimationFrame(tick);
return()=>{cancelAnimationFrame(raf);observer.disconnect();io.disconnect();window.removeEventListener('scroll',scroll);window.removeEventListener('pointermove',pointer);document.removeEventListener('visibilitychange',visibility);renderer.domElement.removeEventListener('webglcontextlost',contextLost);const geoms=new Set<THREE.BufferGeometry>();const mats=new Set<THREE.Material>();scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)geoms.add(m.geometry);if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>mats.add(x))});geoms.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove()};},[theme,inline]);return <div ref={host} className={`world-scene ${inline?'inline':''} ${failed?'scene-fallback':''}`} aria-hidden="true">{failed&&<span>✦</span>}</div>}
